# Generated by Django 5.1.4 on 2024-12-15 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(max_length=255)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(limit_choices_to={'profile__role': 'administrator'}, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('user_affected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_by_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('consultant', models.ForeignKey(limit_choices_to={'profile__role': 'consultant'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_consultant', to=settings.AUTH_USER_MODEL)),
                ('relief_recipient', models.ForeignKey(limit_choices_to={'profile__role': 'relief_recipient'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('relief_recipient', 'Relief Recipient'), ('consultant', 'Consultant'), ('administrator', 'Administrator')], default='relief_recipient', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
